In [17]:
import numpy as np
import pandas as pd

In [18]:

df = pd.read_csv('cars.csv')

In [19]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [20]:

df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [21]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [22]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [23]:
df['brand'].nunique()

32

In [24]:
df['fuel'].nunique()

4

<h2>1. OneHotEncoding using Pandas</h2>

pd.get_dummies() uses One-Hot Encoding logic

It is Pandas’ built-in implementation of one-hot encoding.

In [25]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

<h2>2. K-1 OneHotEncoding</h2>

In [26]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

# What it does
#     Performs One-Hot Encoding
#     Drops one dummy column per categorical feature
#     Keeps k−1 columns instead of k

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

<h2>3. OneHotEncoding using Sklearn</h2>

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [28]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
ohe=OneHotEncoder()

here what we have done that we have first take two columns fuel and owner and applied one hot  encoding 

then with help of np.hstack we are joining oneHot Encoded data with first two columns that are brand and km_driven (horizontal stacking)

In [33]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [32]:

Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3

SyntaxError: invalid syntax (3242365037.py, line 1)

In [34]:
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

In [35]:
X_train[['brand','km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], shape=(6502, 2), dtype=object)

In [36]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 11)

to drop first column of category we will use drop='first'

In [54]:
ohe1=OneHotEncoder(drop='first',sparse_output=False)

In [55]:
#X_train_new1=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
#when we are using sparse_output+False we dont need to write toarray because without that sparse matrix was formed which now it will not form we will get simpe numpy array

X_train_new1=ohe.fit_transform(X_train[['fuel','owner']])

In [56]:
print(type(X_train[['brand','km_driven']].values))
print(type(X_train_new1))

<class 'numpy.ndarray'>
<class 'scipy.sparse._csr.csr_matrix'>

In [57]:
X_test_new1=ohe.transform(X_test[['fuel','owner']])

In [58]:
X_train_new1.shape

(6502, 9)

<h2>OneHotEncoding with Top Categories</h2>

In [61]:
counts = df['brand'].value_counts()
print(counts)

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [62]:
df['brand'].nunique()
threshold = 100

In [63]:
repl = counts[counts <= threshold].index

In [64]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7144,False,False,False,False,False,False,False,False,False,False,False,False,True
7531,False,False,False,False,False,False,False,False,False,True,False,False,False
5473,False,False,False,True,False,False,False,False,False,False,False,False,False
1096,False,False,False,False,False,False,False,False,False,False,False,False,True
7913,False,False,False,False,False,False,True,False,False,False,False,False,False