In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

<h2>Working with dates</h2>

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h4>1. Extract year</h4>

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
953 2018-11-24        1848       14     120       2018
917 2019-01-25        1613       28       6       2019
732 2019-08-15        5143       16       2       2019
147 2019-12-09        5290        3     139       2019
310 2018-11-20        1533       18       8       2018

<h4>2. Extract Month</h4>

In [10]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [11]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

<h4>Extract Days</h4>

In [12]:
date['date_day'] = date['date'].dt.day #mahine ka kon sa din chl raha hai

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek #hafte ka kon sa din chal raha hai

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [14]:

# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [15]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

<h4>Extract week of the year</h4>

🔹 Why isocalendar()?

ISO standard defines:

    Weeks start on Monday
    Week 1 = first week with at least 4 days in the new year

This is industry-standard.

In [18]:
date['date_week'] = date['date'].dt.isocalendar().week.astype(int) #kon sa week hai


date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

<h2>Extract Quarter</h2>

In [19]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

<h2>Extract Semester</h2>

In [20]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

<h2>Extract Time elapsed between dates
</h2>

In [21]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 1, 26, 11, 30, 38, 954551)

In [22]:
today - date['date']

0     2239 days 11:30:38.954551
1     2721 days 11:30:38.954551
2     2652 days 11:30:38.954551
3     2354 days 11:30:38.954551
4     2577 days 11:30:38.954551
                 ...
995   2667 days 11:30:38.954551
996   2608 days 11:30:38.954551
997   2456 days 11:30:38.954551
998   2521 days 11:30:38.954551
999   2295 days 11:30:38.954551
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
(today - date['date']).dt.days

0      2239
1      2721
2      2652
3      2354
4      2577
       ...
995    2667
996    2608
997    2456
998    2521
999    2295
Name: date, Length: 1000, dtype: int64

In [27]:
# Months passed

months_passed = np.round(
    (today - date['date']) / np.timedelta64(1, 'D') / 30,
    0
)

months_passed

0      75.0
1      91.0
2      88.0
3      78.0
4      86.0
       ...
995    89.0
996    87.0
997    82.0
998    84.0
999    77.0
Name: date, Length: 1000, dtype: float64

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [29]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [31]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

<h2>
Extract Time part</h2>

In [32]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

<h2>Time difference</h2>

In [33]:
today - time['date']

0     4425 days 10:40:38.954551
1     4289 days 11:50:38.954551
2     4775 days 11:09:38.954551
3     4077 days 10:59:38.954551
4     4474 days 12:19:38.954551
                 ...
995   5064 days 10:40:38.954551
996   4385 days 12:16:38.954551
997   4850 days 11:53:38.954551
998   4966 days 11:56:38.954551
999   4238 days 12:05:38.954551
Name: date, Length: 1000, dtype: timedelta64[ns]

In [34]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.823584e+08
1      3.706122e+08
2      4.126002e+08
3      3.522924e+08
4      3.865980e+08
           ...
995    4.375680e+08
996    3.789082e+08
997    4.190828e+08
998    4.291054e+08
999    3.662067e+08
Name: date, Length: 1000, dtype: float64

In [35]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.372641e+06
1      6.176871e+06
2      6.876670e+06
3      5.871540e+06
4      6.443300e+06
           ...
995    7.292801e+06
996    6.315137e+06
997    6.984714e+06
998    7.151757e+06
999    6.103446e+06
Name: date, Length: 1000, dtype: float64

In [36]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      106210.677487
1      102947.844154
2      114611.160821
3       97858.994154
4      107388.327487
           ...
995    121546.677487
996    105252.277487
997    116411.894154
998    119195.944154
999    101724.094154
Name: date, Length: 1000, dtype: float64