In [1]:
import pandas as pd
import requests

In [2]:
response=requests.get('https://api.freeapi.app/api/v1/public/randomusers/user/random')

In [3]:
response.json()

{'statusCode': 200,
 'data': {'gender': 'male',
  'name': {'title': 'Mr', 'first': 'Livio', 'last': 'Leclercq'},
  'location': {'street': {'number': 7695, 'name': 'Rue des Jardins'},
   'city': 'Saint-Denis',
   'state': 'Haute-Marne',
   'country': 'France',
   'postcode': 14393,
   'coordinates': {'latitude': '59.3661', 'longitude': '-147.5639'},
   'timezone': {'offset': '+4:30', 'description': 'Kabul'}},
  'email': 'livio.leclercq@example.com',
  'login': {'uuid': 'b28471be-f23c-4d91-8028-be9dbbb36063',
   'username': 'bigfrog499',
   'password': 'ncc1701d',
   'salt': '8TnP1vr8',
   'md5': '266480e0459961f6d4863508f403d610',
   'sha1': '9d3ee4ca99fbe11c5ea42c7e868442b7a1cccfba',
   'sha256': '2c49a34e303a92b572470c0aefe21fa05e23423817918ec54fff7a172fb06fff'},
  'dob': {'date': '1993-07-12T06:30:24.916Z', 'age': 29},
  'registered': {'date': '2004-09-25T02:05:44.274Z', 'age': 18},
  'phone': '01-50-93-18-83',
  'cell': '06-94-04-68-52',
  'id': 157,
  'picture': {'large': 'https://randomuser.me/api/portraits/men/90.jpg',
   'medium': 'https://randomuser.me/api/portraits/med/men/90.jpg',
   'thumbnail': 'https://randomuser.me/api/portraits/thumb/men/90.jpg'},
  'nat': 'FR'},
 'message': 'Random user fetched successfully',
 'success': True}

In [4]:
response.json()['data']

{'gender': 'male',
 'name': {'title': 'Mr', 'first': 'Livio', 'last': 'Leclercq'},
 'location': {'street': {'number': 7695, 'name': 'Rue des Jardins'},
  'city': 'Saint-Denis',
  'state': 'Haute-Marne',
  'country': 'France',
  'postcode': 14393,
  'coordinates': {'latitude': '59.3661', 'longitude': '-147.5639'},
  'timezone': {'offset': '+4:30', 'description': 'Kabul'}},
 'email': 'livio.leclercq@example.com',
 'login': {'uuid': 'b28471be-f23c-4d91-8028-be9dbbb36063',
  'username': 'bigfrog499',
  'password': 'ncc1701d',
  'salt': '8TnP1vr8',
  'md5': '266480e0459961f6d4863508f403d610',
  'sha1': '9d3ee4ca99fbe11c5ea42c7e868442b7a1cccfba',
  'sha256': '2c49a34e303a92b572470c0aefe21fa05e23423817918ec54fff7a172fb06fff'},
 'dob': {'date': '1993-07-12T06:30:24.916Z', 'age': 29},
 'registered': {'date': '2004-09-25T02:05:44.274Z', 'age': 18},
 'phone': '01-50-93-18-83',
 'cell': '06-94-04-68-52',
 'id': 157,
 'picture': {'large': 'https://randomuser.me/api/portraits/men/90.jpg',
  'medium': 'https://randomuser.me/api/portraits/med/men/90.jpg',
  'thumbnail': 'https://randomuser.me/api/portraits/thumb/men/90.jpg'},
 'nat': 'FR'}

In [7]:
pd.DataFrame(response.json()['data'])

,gender,name,location,email,login,dob,registered,phone,cell,id,picture,nat
title,male,Mr,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
first,male,Livio,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
last,male,Leclercq,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
street,male,NaN,"{'number': 7695, 'name': 'Rue des Jardins'}",livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
city,male,NaN,Saint-Denis,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
state,male,NaN,Haute-Marne,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
country,male,NaN,France,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
postcode,male,NaN,14393,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
coordinates,male,NaN,"{'latitude': '59.3661', 'longitude': '-147.5639'}",livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
timezone,male,NaN,"{'offset': '+4:30', 'description': 'Kabul'}",livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
uuid,male,NaN,NaN,livio.leclercq@example.com,b28471be-f23c-4d91-8028-be9dbbb36063,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
username,male,NaN,NaN,livio.leclercq@example.com,bigfrog499,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
password,male,NaN,NaN,livio.leclercq@example.com,ncc1701d,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
salt,male,NaN,NaN,livio.leclercq@example.com,8TnP1vr8,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
md5,male,NaN,NaN,livio.leclercq@example.com,266480e0459961f6d4863508f403d610,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
sha1,male,NaN,NaN,livio.leclercq@example.com,9d3ee4ca99fbe11c5ea42c7e868442b7a1cccfba,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
sha256,male,NaN,NaN,livio.leclercq@example.com,2c49a34e303a92b572470c0aefe21fa05e23423817918e...,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
date,male,NaN,NaN,livio.leclercq@example.com,NaN,1993-07-12T06:30:24.916Z,2004-09-25T02:05:44.274Z,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
age,male,NaN,NaN,livio.leclercq@example.com,NaN,29,18,01-50-93-18-83,06-94-04-68-52,157,NaN,FR
large,male,NaN,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,https://randomuser.me/api/portraits/men/90.jpg,FR
medium,male,NaN,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,https://randomuser.me/api/portraits/med/men/90...,FR
thumbnail,male,NaN,NaN,livio.leclercq@example.com,NaN,NaN,NaN,01-50-93-18-83,06-94-04-68-52,157,https://randomuser.me/api/portraits/thumb/men/...,FR

In [9]:
pd.DataFrame(response.json()['data']).head(3)[['gender','email']]

      gender                       email
title   male  livio.leclercq@example.com
first   male  livio.leclercq@example.com
last    male  livio.leclercq@example.com